{% set name = "pytest-emoji" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest-emoji-{{ version }}.tar.gz
  sha256: e1bd4790d87649c2d09c272c88bdfc4d37c1cc7c7a46583087d7c510944571e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pytest >=4.2.1
    - python >={{ python_min }}

test:
  imports:
    - pytest_emoji
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hackebrot/pytest-emoji
  summary: A pytest plugin that adds emojis to your test result report
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
